# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addInterval.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addInterval(object):
    def setupUi(self, addInterval):
        addInterval.setObjectName("addInterval")
        addInterval.resize(343, 300)
        self.label_24 = QtWidgets.QLabel(addInterval)
        self.label_24.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.combo_borehole = QtWidgets.QComboBox(addInterval)
        self.combo_borehole.setGeometry(QtCore.QRect(170, 27, 113, 20))
        self.combo_borehole.setObjectName("combo_borehole")
        self.rbtn_oneInterval = QtWidgets.QRadioButton(addInterval)
        self.rbtn_oneInterval.setGeometry(QtCore.QRect(40, 70, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbtn_oneInterval.setFont(font)
        self.rbtn_oneInterval.setChecked(True)
        self.rbtn_oneInterval.setObjectName("rbtn_oneInterval")
        self.label_25 = QtWidgets.QLabel(addInterval)
        self.label_25.setGeometry(QtCore.QRect(40, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(addInterval)
        self.label_26.setGeometry(QtCore.QRect(40, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.line_startPoint = QtWidgets.QLineEdit(addInterval)
        self.line_startPoint.setGeometry(QtCore.QRect(190, 107, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_startPoint.setFont(font)
        self.line_startPoint.setObjectName("line_startPoint")
        self.line_endPoint = QtWidgets.QLineEdit(addInterval)
        self.line_endPoint.setGeometry(QtCore.QRect(190, 147, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_endPoint.setFont(font)
        self.line_endPoint.setObjectName("line_endPoint")
        self.rbtn_moreInterval = QtWidgets.QRadioButton(addInterval)
        self.rbtn_moreInterval.setGeometry(QtCore.QRect(40, 190, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbtn_moreInterval.setFont(font)
        self.rbtn_moreInterval.setObjectName("rbtn_moreInterval")
        self.label_27 = QtWidgets.QLabel(addInterval)
        self.label_27.setEnabled(False)
        self.label_27.setGeometry(QtCore.QRect(40, 220, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.btn_selectFile = QtWidgets.QToolButton(addInterval)
        self.btn_selectFile.setEnabled(False)
        self.btn_selectFile.setGeometry(QtCore.QRect(210, 227, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_selectFile.setFont(font)
        self.btn_selectFile.setObjectName("btn_selectFile")
        self.btn_cancel = QtWidgets.QPushButton(addInterval)
        self.btn_cancel.setGeometry(QtCore.QRect(50, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_add = QtWidgets.QPushButton(addInterval)
        self.btn_add.setGeometry(QtCore.QRect(200, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(addInterval)
        QtCore.QMetaObject.connectSlotsByName(addInterval)

    def retranslateUi(self, addInterval):
        _translate = QtCore.QCoreApplication.translate
        addInterval.setWindowTitle(_translate("addInterval", "Добавить интервал перфорации"))
        self.label_24.setText(_translate("addInterval", "Скважина"))
        self.rbtn_oneInterval.setText(_translate("addInterval", "Один интервал"))
        self.label_25.setText(_translate("addInterval", "Начальная глубина, м"))
        self.label_26.setText(_translate("addInterval", "Конечная глубина, м"))
        self.rbtn_moreInterval.setText(_translate("addInterval", "Несколько интервалов"))
        self.label_27.setText(_translate("addInterval", "Интервалы перфорации"))
        self.btn_selectFile.setText(_translate("addInterval", "Выбрать файл"))
        self.btn_cancel.setText(_translate("addInterval", "Отмена"))
        self.btn_add.setText(_translate("addInterval", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addInterval = QtWidgets.QDialog()
    ui = Ui_addInterval()
    ui.setupUi(addInterval)
    addInterval.show()
    sys.exit(app.exec_())
