# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\changeInterval.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_changeInterval(object):
    def setupUi(self, changeInterval):
        changeInterval.setObjectName("changeInterval")
        changeInterval.resize(339, 288)
        self.label_28 = QtWidgets.QLabel(changeInterval)
        self.label_28.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.combo_numberBorehole = QtWidgets.QComboBox(changeInterval)
        self.combo_numberBorehole.setGeometry(QtCore.QRect(190, 27, 113, 20))
        self.combo_numberBorehole.setObjectName("combo_numberBorehole")
        self.label_29 = QtWidgets.QLabel(changeInterval)
        self.label_29.setGeometry(QtCore.QRect(20, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(changeInterval)
        self.label_30.setGeometry(QtCore.QRect(40, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(changeInterval)
        self.label_31.setGeometry(QtCore.QRect(40, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.btn_cancel = QtWidgets.QPushButton(changeInterval)
        self.btn_cancel.setGeometry(QtCore.QRect(50, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_change = QtWidgets.QPushButton(changeInterval)
        self.btn_change.setGeometry(QtCore.QRect(190, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_change.setFont(font)
        self.btn_change.setObjectName("btn_change")
        self.line_startPoint = QtWidgets.QLineEdit(changeInterval)
        self.line_startPoint.setGeometry(QtCore.QRect(190, 127, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_startPoint.setFont(font)
        self.line_startPoint.setObjectName("line_startPoint")
        self.line_endPoint = QtWidgets.QLineEdit(changeInterval)
        self.line_endPoint.setGeometry(QtCore.QRect(190, 177, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_endPoint.setFont(font)
        self.line_endPoint.setObjectName("line_endPoint")
        self.combo_Interval = QtWidgets.QComboBox(changeInterval)
        self.combo_Interval.setGeometry(QtCore.QRect(190, 77, 113, 20))
        self.combo_Interval.setObjectName("combo_Interval")

        self.retranslateUi(changeInterval)
        QtCore.QMetaObject.connectSlotsByName(changeInterval)

    def retranslateUi(self, changeInterval):
        _translate = QtCore.QCoreApplication.translate
        changeInterval.setWindowTitle(_translate("changeInterval", "Изменить интервалы перфорации"))
        self.label_28.setText(_translate("changeInterval", "Номер скважины"))
        self.label_29.setText(_translate("changeInterval", "Интервал перфорации"))
        self.label_30.setText(_translate("changeInterval", "Начальная глубина, м"))
        self.label_31.setText(_translate("changeInterval", "Конечная глубина, м"))
        self.btn_cancel.setText(_translate("changeInterval", "Отмена"))
        self.btn_change.setText(_translate("changeInterval", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changeInterval = QtWidgets.QDialog()
    ui = Ui_changeInterval()
    ui.setupUi(changeInterval)
    changeInterval.show()
    sys.exit(app.exec_())
