# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\deleteBorehole.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteBorehole(object):
    def setupUi(self, deleteBorehole):
        deleteBorehole.setObjectName("deleteBorehole")
        deleteBorehole.resize(311, 127)
        self.centralwidget = QtWidgets.QWidget(deleteBorehole)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(50, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(170, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName("btn_delete")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(50, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.combo_numberBorehole = QtWidgets.QComboBox(self.centralwidget)
        self.combo_numberBorehole.setGeometry(QtCore.QRect(160, 17, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_numberBorehole.setFont(font)
        self.combo_numberBorehole.setObjectName("combo_numberBorehole")
        deleteBorehole.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(deleteBorehole)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 311, 21))
        self.menubar.setObjectName("menubar")
        deleteBorehole.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(deleteBorehole)
        self.statusbar.setObjectName("statusbar")
        deleteBorehole.setStatusBar(self.statusbar)

        self.retranslateUi(deleteBorehole)
        QtCore.QMetaObject.connectSlotsByName(deleteBorehole)

    def retranslateUi(self, deleteBorehole):
        _translate = QtCore.QCoreApplication.translate
        deleteBorehole.setWindowTitle(_translate("deleteBorehole", "Удалить скважину"))
        self.btn_cancel.setText(_translate("deleteBorehole", "Отмена"))
        self.btn_delete.setText(_translate("deleteBorehole", "Удалить"))
        self.label_35.setText(_translate("deleteBorehole", "Номер скважины"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteBorehole = QtWidgets.QMainWindow()
    ui = Ui_deleteBorehole()
    ui.setupUi(deleteBorehole)
    deleteBorehole.show()
    sys.exit(app.exec_())
