# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\deleteCycle.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteCycle(object):
    def setupUi(self, deleteCycle):
        deleteCycle.setObjectName("deleteCycle")
        deleteCycle.resize(334, 184)
        self.label_52 = QtWidgets.QLabel(deleteCycle)
        self.label_52.setGeometry(QtCore.QRect(60, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(deleteCycle)
        self.label_53.setGeometry(QtCore.QRect(60, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.combo_numberBorehole = QtWidgets.QComboBox(deleteCycle)
        self.combo_numberBorehole.setGeometry(QtCore.QRect(180, 27, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_numberBorehole.setFont(font)
        self.combo_numberBorehole.setObjectName("combo_numberBorehole")
        self.combo_numberPCO = QtWidgets.QComboBox(deleteCycle)
        self.combo_numberPCO.setGeometry(QtCore.QRect(180, 77, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_numberPCO.setFont(font)
        self.combo_numberPCO.setObjectName("combo_numberPCO")
        self.btn_cancel = QtWidgets.QPushButton(deleteCycle)
        self.btn_cancel.setGeometry(QtCore.QRect(30, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_delete = QtWidgets.QPushButton(deleteCycle)
        self.btn_delete.setGeometry(QtCore.QRect(190, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName("btn_delete")

        self.retranslateUi(deleteCycle)
        QtCore.QMetaObject.connectSlotsByName(deleteCycle)

    def retranslateUi(self, deleteCycle):
        _translate = QtCore.QCoreApplication.translate
        deleteCycle.setWindowTitle(_translate("deleteCycle", "Удалить цикл ПЦО"))
        self.label_52.setText(_translate("deleteCycle", "Номер скважины"))
        self.label_53.setText(_translate("deleteCycle", "Номер ПЦО"))
        self.btn_cancel.setText(_translate("deleteCycle", "Отмена"))
        self.btn_delete.setText(_translate("deleteCycle", "Удалить"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    deleteCycle = QtWidgets.QDialog()
    ui = Ui_deleteCycle()
    ui.setupUi(deleteCycle)
    deleteCycle.show()
    sys.exit(app.exec_())
