# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\deleteInterval.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteInterval(object):
    def setupUi(self, deleteInterval):
        deleteInterval.setObjectName("deleteInterval")
        deleteInterval.resize(395, 177)
        self.label_32 = QtWidgets.QLabel(deleteInterval)
        self.label_32.setGeometry(QtCore.QRect(40, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(deleteInterval)
        self.label_33.setGeometry(QtCore.QRect(40, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.combo_numberBorehole = QtWidgets.QComboBox(deleteInterval)
        self.combo_numberBorehole.setGeometry(QtCore.QRect(220, 27, 113, 20))
        self.combo_numberBorehole.setObjectName("combo_numberBorehole")
        self.combo_Interval = QtWidgets.QComboBox(deleteInterval)
        self.combo_Interval.setGeometry(QtCore.QRect(220, 77, 113, 20))
        self.combo_Interval.setObjectName("combo_Interval")
        self.btn_cancel = QtWidgets.QPushButton(deleteInterval)
        self.btn_cancel.setGeometry(QtCore.QRect(80, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_delete = QtWidgets.QPushButton(deleteInterval)
        self.btn_delete.setGeometry(QtCore.QRect(230, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName("btn_delete")

        self.retranslateUi(deleteInterval)
        QtCore.QMetaObject.connectSlotsByName(deleteInterval)

    def retranslateUi(self, deleteInterval):
        _translate = QtCore.QCoreApplication.translate
        deleteInterval.setWindowTitle(_translate("deleteInterval", "Удалить интервал перфорации"))
        self.label_32.setText(_translate("deleteInterval", "Номер скважины"))
        self.label_33.setText(_translate("deleteInterval", "Интервал перфорации"))
        self.btn_cancel.setText(_translate("deleteInterval", "Отмена"))
        self.btn_delete.setText(_translate("deleteInterval", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteInterval = QtWidgets.QDialog()
    ui = Ui_deleteInterval()
    ui.setupUi(deleteInterval)
    deleteInterval.show()
    sys.exit(app.exec_())
